name: flutter_riverpod_todo_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.2.6+4

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  backdrop: ^0.9.1
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  share_plus: ^7.2.2
  file_picker: ^6.1.1
  carbon_icons: ^0.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300